<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SignAssembly>False</SignAssembly>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
    <PackageReference Include="SharpHook" Version="7.1.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\OneDrive\Pulpit\Audacity\BroAudio\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
